#!/usr/bin/env python3
"""
gen_verilator_f.py -- give the editor's Verilator lint the context CI has.

An editor lints one file at a time. Without a filelist it cannot find
qnsc_pkg or the vendored modules a wrapper instantiates, so every wrapper
shows "Import package not found" and "Cannot find file containing module"
although `make lint` is clean.

This writes .vscode/verilator.f: a -y search directory for every directory a
design/*/*.f filelist compiles from, their +incdir+ lines, every
design/*/waivers.vlt, and .vscode/verilator_vendor.vlt, which hides warnings
inside vendor/ (never edited, so not ours to fix). Verilator then
finds a package or module by its file name, as CI does through the filelists.

Re-run after adding a block or vendoring an IP:  make ide
"""
from __future__ import annotations

from pathlib import Path

REPO = Path(__file__).resolve().parent.parent.parent
OUT = REPO / ".vscode" / "verilator.f"
VENDOR_VLT = REPO / ".vscode" / "verilator_vendor.vlt"


def main() -> None:
    dirs: set[Path] = set()
    incdirs: set[Path] = set()
    for flist in sorted((REPO / "design").glob("*/*.f")):
        for raw in flist.read_text(errors="ignore").splitlines():
            line = raw.split("//")[0].strip()
            if not line or line.startswith("#"):
                continue
            for tok in line.split():
                if tok.startswith("+incdir+"):
                    for d in filter(None, tok[len("+incdir+"):].split("+")):
                        incdirs.add((flist.parent / d).resolve())
                elif tok.endswith((".sv", ".v")):
                    dirs.add((flist.parent / tok).resolve().parent)
    for rtl in (REPO / "design").glob("*/rtl"):
        dirs.add(rtl.resolve())

    waivers = sorted((REPO / "design").glob("*/waivers.vlt"))

    rel = lambda p: p.relative_to(REPO).as_posix()
    lines = [
        "// Generated by flow/ide/gen_verilator_f.py (make ide). Do not edit.",
        "// Search paths for the editor's single-file Verilator lint, and every",
        "// block's lint waivers, so the editor hides what make lint waives.",
        "-Wno-fatal",
        rel(VENDOR_VLT),
        *[rel(w) for w in waivers],
        *[f"+incdir+{rel(d)}" for d in sorted(incdirs)],
        *[f"-y {rel(d)}" for d in sorted(dirs)],
    ]
    OUT.parent.mkdir(exist_ok=True)
    # Vendored IP is never edited, so its warnings are not ours to fix; the
    # editor hides them. make lint still prints them in CI.
    VENDOR_VLT.write_text('`verilator_config\n'
                          '// Generated by flow/ide/gen_verilator_f.py. Do not edit.\n'
                          'lint_off -file "*vendor/*"\n')
    OUT.write_text("\n".join(lines) + "\n")
    print(f"wrote {rel(OUT)}: {len(dirs)} search dirs, {len(incdirs)} include dirs")


if __name__ == "__main__":
    main()
