`timescale 1ns/1ps

// QNSC wrapper of m_qnsc_syscsr_csr: the QSoC SYSCSR, the system status
// registers on APB_M1.
// Spec: doc/specs/QNSC_SYSCSR_MAS.md.
//
// Edit this .src.sv, then `make wrap BLOCK=syscsr`: emacs verilog-mode expands
// the AUTO comments and writes rtl/m_qnsc_wrap_syscsr.sv, the file syscsr.f
// compiles. Template functions: doc/rules/EMACS_quick_guide.pdf.
//
// Declare no port by hand: map every port of the generated module in the
// AUTO_TEMPLATE, so the AUTOs declare them.
//
// Wrapper = core + bridge. The core is m_qnsc_syscsr_csr, generated by
// nguyenquanicd/APB-CSR-Generator from util/gen/syscsr/syscsr_workbook.xlsx; it
// already speaks APB: no bridge. The wrapper renames its ports to the Naming
// Rule and drives its option and constant inputs (MAS Table 10-1); it adds no
// logic.

// This wrapper is IP: it imports no chip package and declares no parameter.
// CHIP_ID_REV arrives on i_cfg_chip_id, tied by design/top to qnsc_pkg::C_CHIP_ID.
module m_qnsc_wrap_syscsr
(
//---------------------------------------------------------------
// Clock/Reset: SCRC o_clk_pbus (never gated) and o_rst_n_por, never
// o_rst_n_pbus: RESET_CAUSE must survive a WDT or software reset (MAS 7.4)
//---------------------------------------------------------------
/*AUTOINPUT("^i_clk\|^i_rst")*/
// Beginning of automatic inputs (from unused autoinst inputs)
input                   i_clk_cpu,              // To u_csr of m_qnsc_syscsr_csr.v
input                   i_rst_n_por,            // To u_csr of m_qnsc_syscsr_csr.v
// End of automatics

//---------------------------------------------------------------
// Bus interface (APB slave, APB_M1)
//---------------------------------------------------------------
/*AUTOINPUT("^i_bus_apb")*/
// Beginning of automatic inputs (from unused autoinst inputs)
input [11:0]            i_bus_apb_paddr,        // To u_csr of m_qnsc_syscsr_csr.v
input                   i_bus_apb_penable,      // To u_csr of m_qnsc_syscsr_csr.v
input [2:0]             i_bus_apb_pprot,        // To u_csr of m_qnsc_syscsr_csr.v
input                   i_bus_apb_psel,         // To u_csr of m_qnsc_syscsr_csr.v
input [3:0]             i_bus_apb_pstrb,        // To u_csr of m_qnsc_syscsr_csr.v
input [31:0]            i_bus_apb_pwdata,       // To u_csr of m_qnsc_syscsr_csr.v
input                   i_bus_apb_pwrite,       // To u_csr of m_qnsc_syscsr_csr.v
// End of automatics
/*AUTOOUTPUT("^o_bus_apb")*/
// Beginning of automatic outputs (from unused autoinst outputs)
output [31:0]           o_bus_apb_prdata,       // From u_csr of m_qnsc_syscsr_csr.v
output                  o_bus_apb_pready,       // From u_csr of m_qnsc_syscsr_csr.v
output                  o_bus_apb_pslverr,      // From u_csr of m_qnsc_syscsr_csr.v
// End of automatics

//---------------------------------------------------------------
// From SCRC: reset-cause set enables, domain reset status
//---------------------------------------------------------------
/*AUTOINPUT("^i_cause\|^i_domain")*/
// Beginning of automatic inputs (from unused autoinst inputs)
input                   i_cause_we_sw,          // To u_csr of m_qnsc_syscsr_csr.v
input                   i_cause_we_wdt,         // To u_csr of m_qnsc_syscsr_csr.v
input [31:0]            i_domain_rst_stat,      // To u_csr of m_qnsc_syscsr_csr.v, ...
// End of automatics

//---------------------------------------------------------------
// Chip configuration, tied by design/top from qnsc_pkg
//---------------------------------------------------------------
/*AUTOINPUT("^i_cfg")*/
// Beginning of automatic inputs (from unused autoinst inputs)
input [31:0]            i_cfg_chip_id          // To u_csr of m_qnsc_syscsr_csr.v
// End of automatics

//---------------------------------------------------------------
// Others -- must stay empty once the template below is complete
//---------------------------------------------------------------
/*AUTOINOUT*/
/*AUTOINPUT*/
/*AUTOOUTPUT*/
);

/*AUTOWIRE*/

//---------------------------------------------------------------
// Integration policy (QNSC_SYSCSR_MAS 5, 6, 10)
//---------------------------------------------------------------
//   0x00 RESET_CAUSE        W1C  reset 0x0000_0001  por / wdt / soft
//   0x04 DOMAIN_RST_STATUS  RO   live               bit n = ~o_rst_n_<d>
//   0x08 CHIP_ID_REV        RO   i_cfg_chip_id      'QSOC'
//
// - PADDR: P_BUS passes 12 bits; the generator decodes 16, the top 4 are 0.
// - PPROT is connected but not checked (i_protect_en = 0); PSLVERR is enabled
//   (misaligned address or partial strobe).
// - RESET_CAUSE: por comes from the reset value, so its hardware write is off;
//   wdt and soft are set by the SCRC levels i_cause_we_*, held for the whole
//   reset (QNSC_SCRC_MAS 7.7). The generator's per-field outputs are unused.
// - DOMAIN_RST_STATUS: bit map of QNSC_SCRC_MAS Table 6-3; bits 13 and 30:18
//   do not exist (reserved, read 0).

/*AUTO_LISP(setq verilog-auto-inout-ignore-regexp
  (concat
  "unuse_inout"
  "\\|unuse_inout"
  ))
*/

/*AUTO_LISP(setq verilog-auto-input-ignore-regexp
  (concat
  "^w_"
  "\\|unuse_input"
  ))
*/

/*AUTO_LISP(setq verilog-auto-output-ignore-regexp
  (concat
  "^w_"
  "\\|unuse_output"
  ))
*/

// Map every port of the generated module to a QNSC name. First match wins;
// [] keeps the width.
/* m_qnsc_syscsr_csr AUTO_TEMPLATE(
    .i_bus_clk                       (i_clk_cpu),
    .i_bus_rstn                      (i_rst_n_por),
    .i_paddr                         ({4'd0, i_bus_apb_paddr[11:0]}), // contract: meta.apb_paddr_width
    .i_protect_en                    (1'b0),
    .i_slverr_en                     (1'b1),
    .i_p\(.*\)                       (i_bus_apb_p\1[]),
    .o_p\(.*\)                       (o_bus_apb_p\1[]),
    .o_resetcause_\(.*\)             (),
    .i_hw_wdata_resetcause_\(.*\)    (1'b1),
    .i_hw_we_resetcause_cause_por    (1'b0),
    .i_hw_we_resetcause_cause_wdt    (i_cause_we_wdt),
    .i_hw_we_resetcause_cause_soft   (i_cause_we_sw),
    .i_domainrststatus_stat_sbus     (i_domain_rst_stat[0]),
    .i_domainrststatus_stat_pbus     (i_domain_rst_stat[1]),
    .i_domainrststatus_stat_wdt      (i_domain_rst_stat[2]),
    .i_domainrststatus_stat_timer_0  (i_domain_rst_stat[3]),
    .i_domainrststatus_stat_timer_1  (i_domain_rst_stat[4]),
    .i_domainrststatus_stat_uart_0   (i_domain_rst_stat[5]),
    .i_domainrststatus_stat_uart_1   (i_domain_rst_stat[6]),
    .i_domainrststatus_stat_spi      (i_domain_rst_stat[7]),
    .i_domainrststatus_stat_i2c      (i_domain_rst_stat[8]),
    .i_domainrststatus_stat_gpio_0   (i_domain_rst_stat[9]),
    .i_domainrststatus_stat_dma      (i_domain_rst_stat[10]),
    .i_domainrststatus_stat_rom      (i_domain_rst_stat[11]),
    .i_domainrststatus_stat_ram      (i_domain_rst_stat[12]),
    .i_domainrststatus_stat_sysdbg   (i_domain_rst_stat[14]),
    .i_domainrststatus_stat_pwm      (i_domain_rst_stat[15]),
    .i_domainrststatus_stat_gpio_1   (i_domain_rst_stat[16]),
    .i_domainrststatus_stat_gpio_2   (i_domain_rst_stat[17]),
    .i_domainrststatus_stat_cpu      (i_domain_rst_stat[31]),
    .i_chipidrev_chip_id_rev         (i_cfg_chip_id[]),
);
*/
m_qnsc_syscsr_csr u_csr (/*AUTOINST*/
                         // Outputs
                         .o_pslverr             (o_bus_apb_pslverr), // Templated
                         .o_pready              (o_bus_apb_pready), // Templated
                         .o_prdata              (o_bus_apb_prdata[31:0]), // Templated
                         .o_resetcause_cause_por(),              // Templated
                         .o_resetcause_cause_wdt(),              // Templated
                         .o_resetcause_cause_soft(),             // Templated
                         // Inputs
                         .i_bus_clk             (i_clk_cpu),     // Templated
                         .i_bus_rstn            (i_rst_n_por),   // Templated
                         .i_paddr               ({4'd0, i_bus_apb_paddr[11:0]}), // Templated
                         .i_protect_en          (1'b0),          // Templated
                         .i_slverr_en           (1'b1),          // Templated
                         .i_pprot               (i_bus_apb_pprot[2:0]), // Templated
                         .i_pwdata              (i_bus_apb_pwdata[31:0]), // Templated
                         .i_pwrite              (i_bus_apb_pwrite), // Templated
                         .i_penable             (i_bus_apb_penable), // Templated
                         .i_psel                (i_bus_apb_psel), // Templated
                         .i_pstrb               (i_bus_apb_pstrb[3:0]), // Templated
                         .i_hw_wdata_resetcause_cause_por(1'b1), // Templated
                         .i_hw_we_resetcause_cause_por(1'b0),    // Templated
                         .i_hw_wdata_resetcause_cause_wdt(1'b1), // Templated
                         .i_hw_we_resetcause_cause_wdt(i_cause_we_wdt), // Templated
                         .i_hw_wdata_resetcause_cause_soft(1'b1), // Templated
                         .i_hw_we_resetcause_cause_soft(i_cause_we_sw), // Templated
                         .i_domainrststatus_stat_sbus(i_domain_rst_stat[0]), // Templated
                         .i_domainrststatus_stat_pbus(i_domain_rst_stat[1]), // Templated
                         .i_domainrststatus_stat_wdt(i_domain_rst_stat[2]), // Templated
                         .i_domainrststatus_stat_timer_0(i_domain_rst_stat[3]), // Templated
                         .i_domainrststatus_stat_timer_1(i_domain_rst_stat[4]), // Templated
                         .i_domainrststatus_stat_uart_0(i_domain_rst_stat[5]), // Templated
                         .i_domainrststatus_stat_uart_1(i_domain_rst_stat[6]), // Templated
                         .i_domainrststatus_stat_spi(i_domain_rst_stat[7]), // Templated
                         .i_domainrststatus_stat_i2c(i_domain_rst_stat[8]), // Templated
                         .i_domainrststatus_stat_gpio_0(i_domain_rst_stat[9]), // Templated
                         .i_domainrststatus_stat_dma(i_domain_rst_stat[10]), // Templated
                         .i_domainrststatus_stat_rom(i_domain_rst_stat[11]), // Templated
                         .i_domainrststatus_stat_ram(i_domain_rst_stat[12]), // Templated
                         .i_domainrststatus_stat_sysdbg(i_domain_rst_stat[14]), // Templated
                         .i_domainrststatus_stat_pwm(i_domain_rst_stat[15]), // Templated
                         .i_domainrststatus_stat_gpio_1(i_domain_rst_stat[16]), // Templated
                         .i_domainrststatus_stat_gpio_2(i_domain_rst_stat[17]), // Templated
                         .i_domainrststatus_stat_cpu(i_domain_rst_stat[31]), // Templated
                         .i_chipidrev_chip_id_rev(i_cfg_chip_id[31:0])); // Templated

endmodule
// Local Variables:
// verilog-library-flags:("-f filelist_emacs.f")
// verilog-library-extensions:(".v" ".sv")
// verilog-auto-star-expand: nil
// verilog-auto-inst-param-value: t
// indent-tabs-mode: nil
// eval: (setq large-file-warning-threshold nil)
// End:
