#!/usr/bin/env python3
"""Generate the boot ROM contents module m_qnsc_rom_image from rom_image.hex.

QNSC_ROM_MAS V3.1, 7.2: the libraries have no mask ROM and no OTP, so the ROM
contents are a constant case over the 512 word indices, into an output
register loaded when i_mem_oe = 1. No reset, no initial, no memory array:
synthesis maps it to constant logic (ROM_008).

    python3 util/gen_rom.py <rom_image.hex> <out.sv>            generate
    python3 util/gen_rom.py <rom_image.hex> <out.sv> --check    CI: fail if <out.sv>
                                                                 differs from a regeneration
rom_image.hex (design/rom/boot/tools/bin2hex.py): one 32-bit word per line,
word n = bytes 4n..4n+3 of the bootloader binary, byte 4n in bits 7:0; words
past the binary are 0. The generator fails if the image does not fit 2048 bytes
(ROM_006): more than 512 words, or a non-zero word beyond word 511.

The output is deterministic (no date, no path of the machine that ran it), so
a regeneration from the committed hex reproduces the committed module exactly.
"""
import os
import re
import sys

WORDS = 512                      # contract: memory_map.rom.size (2048 B)
AW = 9                           # word index width, [10:2] of the byte address


def read_hex(path):
    words = []
    for n, line in enumerate(open(path, encoding="utf-8"), 1):
        tok = line.split("//")[0].strip()
        if not tok:
            continue
        if not re.fullmatch(r"[0-9a-fA-F]{1,8}", tok):
            sys.exit(f"gen_rom: {path}:{n}: '{tok}' is not a 32-bit hex word")
        words.append(int(tok, 16))
    if len(words) > WORDS:
        extra = [w for w in words[WORDS:] if w]
        if extra:
            sys.exit(f"gen_rom: image is {len(words)} words; the ROM holds {WORDS} (2048 B)")
        words = words[:WORDS]
    return words + [0] * (WORDS - len(words))


def render(words, src_name):
    used = max((i + 1 for i, w in enumerate(words) if w), default=0)
    arms = "\n".join(f"        {AW}'d{i:<3}: r_mem_rdata <= 32'h{w:08X};"
                     for i, w in enumerate(words[:used]))
    return f"""// =============================================================================
// GENERATED by util/gen_rom.py from {src_name} -- DO NOT EDIT.
// Regenerate: make -C design/rom/boot rtl   (or python3 util/gen_rom.py ...)
//
// m_qnsc_rom_image -- boot ROM contents (QNSC_ROM_MAS V3.1, 5, 7.2)
// {WORDS} x 32-bit words at 0x0000_0000; {used} non-zero-tail words, the rest read 0.
// Word n is ROM bytes 4n..4n+3, byte 4n in bits 7:0. Read data is valid in the
// cycle after i_mem_oe = 1, as the AXI4-SRAM controller samples it.
// Constant case into an output register: no reset, no initial, no array.
// =============================================================================
module m_qnsc_rom_image (
  input  logic        i_clk_mem,
  input  logic        i_mem_oe,           // controller o_sram_oe
  input  logic [{AW - 1}:0]  i_mem_addr,         // word index = controller o_sram_addr[10:2]
  output logic [31:0] o_mem_rdata         // word i_mem_addr, the cycle after i_mem_oe
);
  logic [31:0] r_mem_rdata;

  always_ff @(posedge i_clk_mem) begin
    if (i_mem_oe) begin
      case (i_mem_addr)
{arms}
        default: r_mem_rdata <= 32'h00000000;
      endcase
    end
  end

  assign o_mem_rdata = r_mem_rdata;
endmodule
"""


def main():
    args = [a for a in sys.argv[1:] if a != "--check"]
    check = "--check" in sys.argv[1:]
    if len(args) != 2:
        sys.exit(__doc__)
    hex_path, out_path = args
    text = render(read_hex(hex_path), os.path.basename(hex_path))
    if check:
        old = open(out_path, encoding="utf-8").read() if os.path.exists(out_path) else ""
        if old != text:
            sys.exit(f"gen_rom: {out_path} differs from a regeneration of {hex_path}")
        print(f"gen_rom: {out_path} matches {hex_path}")
        return
    os.makedirs(os.path.dirname(os.path.abspath(out_path)), exist_ok=True)
    with open(out_path, "w", encoding="utf-8", newline="\n") as f:
        f.write(text)
    print(f"gen_rom: {hex_path} -> {out_path}")


if __name__ == "__main__":
    main()
