# =============================================================================
# Filelist for the uart block.
#
# This is the single place that says which files build this block, and in what
# order. CI lints the block through this file, so a file not listed here is not
# compiled and not checked.
#
# Rules:
#   - Upstream IP is LISTED here, never copied into rtl/. Paths are relative to
#     this file, so they start with ../../vendor/...
#   - Order matters. Packages and `define files first, then leaf modules, then
#     the modules that instantiate them, then our wrapper last.
#   - Anything under rtl/ is code written here. Anything under ../../vendor/ is
#     not ours -- see vendor/manifest.yml for its pinned commit and licence.
# =============================================================================

# ---- include directories ----------------------------------------------------
# Needed by apb_uart.sv (`include "apb/typedef.svh") and apb_uart_wrap.sv
# (`include "obi/typedef.svh"). Enable with the dependencies below.
# +incdir+../../vendor/pulp-platform/common_cells/include
# +incdir+../../vendor/pulp-platform/apb/include
# +incdir+../../vendor/pulp-platform/obi/include

# ---- upstream IP, in compile order -----------------------------------------
# PENDING (QNSC_UART_MAS 4 and 11, open item of the UART owner): apb_uart needs
# obi_peripherals (obi_uart), obi (apb_to_obi, obi_pkg), apb (typedef.svh),
# common_cells with the src/deprecated shims and tech_cells_generic (tc_sync),
# at the commits of MAS section 4. None is vendored yet, so lint of this block
# fails on the missing modules until they are. Once `util/vendor_ip.py` has
# brought them in, list them here, packages first, in this order:
#   common_cells  cf_math_pkg, then the cc_* cells and the src/deprecated shims
#                 fifo_v3, counter, delta_counter, sync
#   tech_cells_generic  tc_sync
#   obi           obi_pkg, apb_to_obi
#   obi_peripherals/hw/obi_uart  obi_uart_pkg, _baudgen, _interrupts, _modem,
#                 _rx, _tx, _register, obi_uart (upstream Bender.yml order)

# pulp-platform/apb_uart -- apb_uart_wrap joins apb_to_obi and obi_uart;
# reg_uart_wrap.sv (Regbus) is not used.
../../vendor/pulp-platform/apb_uart/src/apb_uart_wrap.sv
../../vendor/pulp-platform/apb_uart/src/apb_uart.sv

# ---- ours -------------------------------------------------------------------
# Generated by `make wrap BLOCK=uart` from rtl/emacs/m_qnsc_wrap_uart.src.sv.
rtl/m_qnsc_wrap_uart.sv
