# =============================================================================
# Filelist for the syscsr block (QNSC_SYSCSR_MAS V3.1).
#
# This is the single place that says which files build this block, and in what
# order. CI lints the block through this file, so a file not listed here is not
# compiled and not checked.
#
# Rules:
#   - Upstream IP is LISTED here, never copied into rtl/. Paths are relative to
#     this file.
#   - Order matters: leaf modules first, then our wrapper last.
#   - Generated RTL lives in ../../util/gen/<name>/ with the workbook that makes
#     it; never edit it, regenerate it.
# =============================================================================

# ---- generated: the register block (APB-CSR-Generator, sheet SYSCSR) --------
# Synchronous option: the generator's models/m_vlsi_synch.sv is not needed.
../../util/gen/syscsr/RTL/m_qnsc_syscsr_csr.sv

# ---- ours ---------------------------------------------------------------------
# Generated by emacs from rtl/emacs/m_qnsc_wrap_syscsr.src.sv (make wrap
# BLOCK=syscsr); never edit it by hand.
rtl/m_qnsc_wrap_syscsr.sv
