# =============================================================================
# Filelist for the rom block (QNSC_ROM_MAS V3.1).
#
# This is the single place that says which files build this block, and in what
# order. CI lints the block through this file, so a file not listed here is not
# compiled and not checked.
#
# Rules:
#   - Upstream IP is LISTED here, never copied into rtl/. Paths are relative to
#     this file, so they start with ../../vendor/...
#   - Order matters. Packages and `define files first, then leaf modules, then
#     the modules that instantiate them, then our wrapper last.
#   - Anything under rtl/ is code written here. Anything under ../../vendor/ is
#     not ours -- see vendor/manifest.yml for its pinned commit and licence.
#
# The ROM reuses the controller of ISRAM and DSRAM
# (nguyenquanicd/AXI4-SRAM-CONTROLLER) with its write channel tied idle; a
# responder in the wrapper answers every write with SLVERR, and the contents
# are the generated constant module m_qnsc_rom_image (util/gen_rom.py).
# =============================================================================

# ---- upstream IP, in compile order -----------------------------------------
../../vendor/nguyenquanicd/AXI4-SRAM-CONTROLLER/rtl/m_vlsi_axfsm.sv
../../vendor/nguyenquanicd/AXI4-SRAM-CONTROLLER/rtl/m_vlsi_fifo.sv
../../vendor/nguyenquanicd/AXI4-SRAM-CONTROLLER/rtl/m_vlsi_arbiter.sv
../../vendor/nguyenquanicd/AXI4-SRAM-CONTROLLER/rtl/m_vlsi_sram_misc.sv
../../vendor/nguyenquanicd/AXI4-SRAM-CONTROLLER/rtl/m_vlsi_axi4_sram.sv

# ---- generated: ROM contents (make -C boot rtl, util/gen_rom.py) -----------
# From util/gen/rom/rom_image.hex, the built bootloader (make -C boot rtl).
../../util/gen/rom/m_qnsc_rom_image.sv

# ---- ours -------------------------------------------------------------------
# m_qnsc_rom_wr_resp: write-error responder (MAS 7.3), hand-written FSM.
# m_qnsc_wrap_rom: generated by emacs from rtl/emacs/m_qnsc_wrap_rom.src.sv
# (make wrap BLOCK=rom); never edit it by hand.
rtl/m_qnsc_rom_wr_resp.sv
rtl/m_qnsc_wrap_rom.sv
